
class Controls
{
public:
// global bools for key controls
bool upkey,                                 // Key States (true / false)
	 downkey,                               // ...
	 leftkey,                               // ...
	 rightkey,                              // ...
	 altleftkey,                            // ...
	 altrightkey,                           // ...
	 wkey,                                  // ...
	 skey,                                  // ...
	 ctrlkey,                               // ...
	 altkey,                                // ...
	 akey,                                  // ...
	 dkey,                                  // ...
	 shiftkey,                              // ...
	 spacebar,                              // ...
	 rightButton,                           // ...
	 leftButton,                            // ...
	 pageupkey,                             // ...
	 pagedownkey;                           // ...

int mouseX, mouseY;
bool przesuwanie;
bool zmianaKoloru;
};